name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo build --workspace --all-features
      - run: cargo clippy --workspace --tests --all-features -- -D warnings
      - run: cargo fmt --all -- --check
      - run: cargo test --workspace --all-features
